name: 'Sync between to S3'
description: ''
inputs:

  dirname:
    description: 'folder to upload'
    required: true
    default: ''
     
  bucketname:
    description: 'Bucket name'
    requred: true
    default: ''

  s3dirname:
    description: 'folder on S3 to upload to'
    requred: true
    default: ''
        
  AWS_KEY_ID:
    required: true

  AWS_ACCESS_KEY:
    required: true

  REGION:
    required: false
    default: "ru-1a"

  DOWNLOAD:
    required: false
    default: "false"

  FILENAME:
    required: false
    default: ""

  ENDPOINT:
    required: false
    default: https://s3.selcdn.ru

runs:
  using: "composite"
  steps: 
    - name: Configure
      shell: bash
      run: |
        aws configure set aws_access_key_id "${{ inputs.AWS_KEY_ID }}"
        aws configure set aws_secret_access_key "${{ inputs.AWS_ACCESS_KEY }}" 
        aws configure set endpoint-url ${{ inputs.ENDPOINT }}
        #aws configure set default.region ${{ inputs.REGION }}
        aws s3 ls --endpoint ${{ inputs.ENDPOINT }} || (echo "bad aws_access_key_id / aws_secret_access_key" && exit 1 )
      
    - name: Sync (UPLOAD)
      if: inputs.DOWNLOAD == 'false'
      shell: bash
      run: |
        ([ -d '${{ inputs.dirname }}' ] && aws s3 sync '${{ inputs.dirname }}' 's3://${{ inputs.bucketname }}/${{ inputs.s3dirname }}' --endpoint ${{ inputs.ENDPOINT }} || (echo 'Bad path ${{ inputs.dirname }}')

    - name: Sync (DOWNLOAD)
      if: inputs.DOWNLOAD == 'true' && inputs.FILENAME == ''
      shell: bash
      run: |
        aws s3 sync --endpoint ${{ inputs.ENDPOINT }} 's3://${{ inputs.bucketname }}/${{ inputs.s3dirname }}' '${{ inputs.dirname }}'

    - name: Copy from Selectel  (DOWNLOAD)
      if: inputs.DOWNLOAD == 'true' && inputs.FILENAME != ''
      shell: bash
      run: |
        aws s3 cp 's3://${{ inputs.bucketname }}/${{ inputs.s3dirname }}/${{ inputs.FILENAME }}' '${{ inputs.dirname }}/${{ inputs.FILENAME }}' --endpoint ${{ inputs.ENDPOINT }}

