name: Upload TEST Selectel

on:
  workflow_dispatch:
    inputs:
      key_id_from:
        description: 'Key id from'     
        required: true
        default: 'false'
      key_secret_from:
        description: 'Key secret from'     
        required: true
        default: 'false'
      bucket_from:
        description: 's3 bucket from'     
        required: true
        default: 'internal'
      dir_from:
        description: 's3 dir from (exmp: testdir/main/yo)'     
        required: false
        default: ''  
      endpoint_from:
        description: 's3 end from'
        required: true
        default: 'https://s3.ru-1.storage.selcloud.ru'
      key_id_to:
        description: 'Key id to'     
        required: true
        default: 'false'
      key_secret_to:
        description: 'Key secret to'     
        required: true
        default: 'false'
      bucket_to:
        description: 's3 bucket to'     
        required: true
        default: 'skazbuka' 
      endpoint_to:
        description: 's3 end to'
        required: true
        default: 'http://s3.mds.yandex.net'
      dir_to:
        description: 's3 dir from (exmp: test/testdir/main/yo)'     
        required: true
        default: 'test'  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Download test
      - name: Sync with AWS (Down)
        uses: Zebrainy/s3-sync-action@syncer
        with:
          dirname: download
          bucketname: ${{ inputs.bucket_from }}
          s3dirname: ${{ inputs.dir_from }}
          DOWNLOAD: true
          AWS_KEY_ID: ${{ inputs.key_id_from }}
          AWS_ACCESS_KEY: ${{ inputs.key_secret_from }}
          ENDPOINT: ${{ inputs.endpoint_from }}

      - name: ls check
        run: find ./download/

      # UPload test
      - name: Sync with AWS (Upload)
        uses: Zebrainy/s3-sync-action@syncer
        with:
          dirname: download
          bucketname: ${{ inputs.bucket_to }}
          s3dirname: ${{ inputs.dir_to }}
          AWS_KEY_ID: ${{ inputs.key_id_to }}
          AWS_ACCESS_KEY: ${{ inputs.key_secret_to }}
          ENDPOINT: ${{ inputs.endpoint_to }}

      
